version: "2.2"

services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=restapi
      - POSTGRES_USER=restapi
      - POSTGRES_DB=restapi
